//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BusinessCardBookForm20180203.rc에서 사용되고 있습니다.
//
#define IDD_BUSINESSCARDBOOKFORM        101
#define IDD_TAKEINFORM                  103
#define IDD_FINDFORM                    105
#define IDD_TAKEOUTFORM                 107
#define IDC_BUTTON_TAKEIN               1001
#define IDC_BUTTON_FIND                 1002
#define IDC_BUTTON_TAKEOUT              1003
#define IDC_BUTTON_ARRANGE              1004
#define IDC_STATIC_PERSONAL_NAME        1005
#define IDC_STATIC_PERSONAL_NAME_PRINT  1006
#define IDC_STATIC_PERSONAL_POSITION    1007
#define IDC_STATIC_PERSONAL_POSITION_PRINT 1008
#define IDC_STATIC_PERSONAL_TELEPHONENUMBER 1009
#define IDC_STATIC_PERSONAL_EMAILADDRESS 1010
#define IDC_STATIC_PERSONAL_TELEPHONENUMBER_PRINT 1011
#define IDC_STATIC_PERSONAL_EMAILADDRESS_PRINT 1012
#define IDC_STATIC_PERSONAL             1013
#define IDC_STATIC_COMPANY_NAME         1014
#define IDC_STATIC_COMPANY_NAME_PRINT   1015
#define IDC_STATIC_COMPANY_ADDRESS      1016
#define IDC_STATIC_COMPANY              1017
#define IDC_STATIC_COMPANY_TELEPHONENUMBER 1018
#define IDC_STATIC_COMPANY_FAXNUMBER    1019
#define IDC_STATIC_BUSINESSCARD         1020
#define IDC_BUTTON_FIRST                1021
#define IDC_STATIC_COMPANY_URL          1022
#define IDC_BUTTON_PREVIOUS             1023
#define IDC_BUTTON_NEXT                 1024
#define IDC_BUTTON_LAST                 1025
#define IDC_EDIT_PERSONAL_NAME          1027
#define IDC_COMBO_PERSONAL_POSITION     1028
#define IDC_STATIC_COMPANY_ADDRESS_PRINT 1029
#define IDC_EDIT_PERSONAL_TELEPHONENUMBER 1029
#define IDC_STATIC_COMPANY_TELEPHONENUMBER_PRINT 1030
#define IDC_EDIT_PERSONAL_EMAILADDRESS  1030
#define IDC_STATIC_COMPANY_FAXNUMBER_PRINT 1031
#define IDC_STATIC_AT                   1031
#define IDC_STATIC_COMPANY_URL_PRINT    1032
#define IDC_COMBO_PERSONAL_EMAILADDRESS 1032
#define IDC_EDIT_COMPANY_NAME           1033
#define IDC_EDIT_COMPANY_ADDRESS        1034
#define IDC_EDIT_COMPANY_TELEPHONENUMBER 1035
#define IDC_BUTTON_SELECT               1035
#define IDC_EDIT_COMPANY_FAXNUMBER      1036
#define IDC_EDIT_NAME                   1036
#define IDC_EDIT_COMPANY_URL            1037
#define IDC_STATIC_NAME                 1037
#define IDC_STATIC_READNAME             1038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
